version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=propelize
      - DB_USER=root
      - DB_PASS=
      - DB_HOST=locahost
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: propelize
    ports:
      - "3306:3306"
